#!/bin/bash
# Set CLASSPATH to working Directory
#export CLASSPATH=/home/burni/Runtime-Tester-Arch

# $1 = (File)   File to be executed
# $2 = (Int)    Number of Threads
# $3 = (Char)   Benchmark size (S,W,A,...)
# $4 = (Int)    Test size (1,2,3,...)

# Test ob Benchmark läuft
./$1 $2 $3
java NPB3_0_JAV.IS -np$2 CLASS=$3

# Executes $4 Tests
counter=1
while [ $counter -le $4 ]
do
./$1 $2 $3 | grep 'Time in'* >> $2-$3.txt
grep -Eo  '[0-9]+([.][0-9]+)' $1-$2.txt >> $1-$2-Times.txt
rm $2-$3.txt
echo "$counter Tests done"
((counter++))
done
echo 'All Tests done'
